### PR TITLE
Make sure the alert buttonLabel is a string

### PR DESCRIPTION
**Pull request by Boosten**
Just a type check to make sure the buttonLabel argument is a string. The fallback to "OK" is already in place.

### CODE REVIEW

**Comment by cordova-qa** [comment]
Cordova CI Build has one or more failures. 

**Commit**     - [Link](https://github.com/apache/cordova-plugin-dialogs/pull/82/commits/5ecb3506e0de87d0465713857af132e68c543f00)
**Dashboard** - [Link](http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-dialogs-pr/30/)

| Builder Name  | Console Output | Test Report | Device Logs  |
|     :---:     |     :---:      |   :---:     |     :---:    |
| [Windows 8.1 Store]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-dialogs-pr/30//PLATFORM=windows-8.1-store/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-dialogs-pr/30//PLATFORM=windows-8.1-store/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-dialogs-pr/30//PLATFORM=windows-8.1-store/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-dialogs-pr/30//PLATFORM=windows-8.1-store/artifact/) |
| [Windows 10  Store]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-dialogs-pr/30//PLATFORM=windows-10-store/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-dialogs-pr/30//PLATFORM=windows-10-store/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-dialogs-pr/30//PLATFORM=windows-10-store/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-dialogs-pr/30//PLATFORM=windows-10-store/artifact/) |
| [Windows 8.1 Phone]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-dialogs-pr/30//PLATFORM=windows-8.1-phone/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-dialogs-pr/30//PLATFORM=windows-8.1-phone/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-dialogs-pr/30//PLATFORM=windows-8.1-phone/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-dialogs-pr/30//PLATFORM=windows-8.1-phone/artifact/) |
| [iOS]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-dialogs-pr/30//PLATFORM=ios/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-dialogs-pr/30//PLATFORM=ios/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-dialogs-pr/30//PLATFORM=ios/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-dialogs-pr/30//PLATFORM=ios/artifact/) |
| [Android]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-dialogs-pr/30//PLATFORM=android/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-dialogs-pr/30//PLATFORM=android/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-dialogs-pr/30//PLATFORM=android/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-dialogs-pr/30//PLATFORM=android/artifact/) |

**Comment by purplecabbage** [comment]
I think we are okay with 
``` 
    alert("What is the meaning of life?", function(){}, "Your Question", 42);
```
also, your code overlooks empty string ... ( "" || "OK") returns OK, but typeof "" IS string.

**Comment by Boosten** [comment]
In case the "buttonLabel" is not a string, the native iOS implementation `showDialogWithMessage` will crash on the `addAction` method because `actionWithTitle` expects a string. 

CDVNotification.m:
`[alertController addAction:[UIAlertAction actionWithTitle:[buttons objectAtIndex:n]
                                                                style:UIAlertActionStyleDefault
                                                              handler:^(UIAlertAction * action)`

**result:**
`-[__NSCFNumber isEqualToString:]: unrecognized selector sent to instance`

So I think it's not superfluous to check whether or not the passed in button is a string.

**Comment by purplecabbage** [comment]
Merged! Thanks @Boosten

**Pull request merged**
