### PR TITLE
add password and login/password input type for prompt.dialogType

### PR DESCRIPTION
**Pull request by tiptronic**
Add two more parameters for configuration of your dialog.prompt:
- inputType            Textbox input type  ("password", "loginpassword" - default: "plain text")
  'password':text-entry field doesn't show the text-input, but dots •
  'loginpassword': shows prompt with login AND password fields (where password fields are obscured)

-obscureText        The input text for the obscured (password) text box, if inputType is 'loginpassword'

notification.js needs to get changed accordingly

### CODE REVIEW

**Comment by toromand** [comment]
Any news on this? Seems like a nice (and needed) feature.
If the original author of the change is not available and not willing to contribute, can someone with sufficient rights "redo" the job and commit properly?

**Comment by purplecabbage** [comment]
Still waiting to hear on the icla 
Also, adding this to iOS only is adding a quirk, not a feature. 
And, spin changes should have accompanying docs changes.

**Comment by toromand** [comment]
Yes, you are right. I noticed late that the proposed change is IOS only.
On the other hand, I know this is easy to implement on Android (similar is already implemented in some forks as numeric pin for instance). I guess other platforms are also possible.
So, you may count this as a feature request :)

**Comment by infil00p** [comment]
So, is this an abandoned PR? I'm going to close this PR in a week unless the conflicts are resolved.

**Pull request closed without merging**
