### PR TITLE
Secure prompt text fields for passwords

### PR DESCRIPTION
**Pull request by WillAnd31**
This PR will add the ability to have secure text input fields (for passwords) on prompts. I've only tested this on iPhone and Android phones. You can use this functionality by using `true` instead of a string for `defaultText` when using the `prompt` method. The regular functionality of `prompt` still works too.

### CODE REVIEW

**Comment by cordova-qa** [comment]
Cordova CI Build has completed successfully. 

**Commit**     - [Link](https://github.com/apache/cordova-plugin-dialogs/pull/71/commits/6ae213f4d70e4c6e8616cb47e0220c9dbed002bb)
**Dashboard** - [Link](http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-dialogs-pr/3/)

| Builder Name  | Console Output | Test Report | Device Logs  |
|     :---:     |     :---:      |   :---:     |     :---:    |
| [Windows 8.1 Store]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-dialogs-pr/3//label=windows-slave,platformName=windows-8.1-store/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-dialogs-pr/3//label=windows-slave,platformName=windows-8.1-store/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-dialogs-pr/3//label=windows-slave,platformName=windows-8.1-store/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-dialogs-pr/3//label=windows-slave,platformName=windows-8.1-store/artifact/) |
| [Windows 10  Store]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-dialogs-pr/3//label=windows-slave,platformName=windows-10-store/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-dialogs-pr/3//label=windows-slave,platformName=windows-10-store/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-dialogs-pr/3//label=windows-slave,platformName=windows-10-store/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-dialogs-pr/3//label=windows-slave,platformName=windows-10-store/artifact/) |
| [Windows 8.1 Phone]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-dialogs-pr/3//label=windows-slave,platformName=windows-8.1-phone/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-dialogs-pr/3//label=windows-slave,platformName=windows-8.1-phone/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-dialogs-pr/3//label=windows-slave,platformName=windows-8.1-phone/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-dialogs-pr/3//label=windows-slave,platformName=windows-8.1-phone/artifact/) |
| [iOS]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-dialogs-pr/3//label=mac-slave,platformName=ios/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-dialogs-pr/3//label=mac-slave,platformName=ios/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-dialogs-pr/3//label=mac-slave,platformName=ios/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-dialogs-pr/3//label=mac-slave,platformName=ios/artifact/) |
| [Android Mac]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-dialogs-pr/3//label=mac-slave,platformName=android/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-dialogs-pr/3//label=mac-slave,platformName=android/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-dialogs-pr/3//label=mac-slave,platformName=android/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-dialogs-pr/3//label=mac-slave,platformName=android/artifact/) |

**Comment by purplecabbage** [comment]
Interesting, and useful. However, you cannot simply shoehorn your api into another value. 
I suggest you add your new boolean to the end of the args:
navigator.notification.prompt(message, promptCallback, [title], [buttonLabels], [defaultText], [secureInput])

The only downside then is just that app developers would have to supply defaultText, but they could just use "" so no biggie.

**Comment by WillAnd31** [comment]
I definitely agree, and that's the ideal way of doing it, and it could even support having the default text be the placeholder in the secure input prompt. I implemented it this way so I wouldn't have to create a PR with ngCordova to support a change in the args for this method, but changing it wouldn't be that hard.

**Comment by pke** [comment]
Instead of adding yet another argument one could also opt to support an `option` object instead/alternatively.
Especially since all those values are optional anyway the API surface would get a lot cleaner `prompt(message, options)`

**Comment by purplecabbage** [comment]
True. But all existing code would break.

**Comment by pke** [comment]
@purplecabbage no, of course one would still support the old signature and emit a deprecation warning. Inspecting the arguments should be pretty easy in that case. If the second argument is not a function but an object then its the new syntax.

**Comment by sagrawal14** [comment]
Unfortunately, this doesn't seem to be working on simulators either on the actual device (I tested in iPhone 6s, iOS 9.3.3).

**Comment by infil00p** [comment]
So, is this an abandoned PR? I'm going to close this PR in a week unless the conflicts are resolved.

**Pull request closed without merging**
