### PR TITLE
feat: Added option to specify the input type of the prompt dialog

### PR DESCRIPTION
**Pull request by bpappin**
I have only implemented it for Android and iOS, with Android being my primary language and iOS being a light secondary skill, so treat accordingly.

I did update the documentation in the JS file.

### CODE REVIEW

**Comment by purplecabbage** [comment]
This pr is conflicted. Please rebase or close.

**Comment by conx2share** [comment]
Wow, this is pretty old.
You can see what the changes were, how about just adding them as a new feature?

**Comment by purplecabbage** [comment]
Closing this.

**Comment by ktran13** [comment]
does anyone know whether this feature was implemented?

**Comment by purplecabbage** [comment]
No, @ktran13, it was not.

**Pull request closed without merging**
