### PR TITLE
CB-10727 Dialogs plugin has warnings on iOS

### PR DESCRIPTION
**Pull request by EddyVerbruggen**
Should fix https://issues.apache.org/jira/browse/CB-10727

### CODE REVIEW

**Comment by jcesarmobile** [comment]
Changes look good to me, but how did you get those error messages? If I open CDVNotification.m on Xcode 7.2.1 I don't get them.

**Comment by EddyVerbruggen** [comment]
Thanks for checking it so quickly.

What gets reported as warnings depends on how strict your Xcode project is set up. In this case fi. that count warning pops up when you enable 'Sign Comparison' (look for it in the Build Settings.

**Comment by jcesarmobile** [comment]
Thanks
That shows the NSUIInteger to int conversion warning
To show the 'action' is shadowing an already declared variable I had to change the Hidden Local Variables to YES.

I'll try to merge it latter.

**Comment by EddyVerbruggen** [comment]
:+1:

**Pull request merged**
